import ipaddress
import json
from pathlib import Path
import shlex
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "safe-ssh-port/safe-ssh-port.sh"
FIXTURE = ROOT / "safe-ssh-port/tests/fixtures/iptables.py"
F2B = "f2b-vpstools-sshd"


def verdict(state, source, port, chain="INPUT"):
    for rule in state[chain]:
        if "-s" in rule and ipaddress.ip_address(source) not in ipaddress.ip_network(rule[rule.index("-s") + 1]):
            continue
        if "--dport" in rule and str(port) != rule[rule.index("--dport") + 1]:
            continue
        if "--dports" in rule and str(port) not in rule[rule.index("--dports") + 1].split(","):
            continue
        if "-i" in rule or "--ctstate" in rule or "-p" in rule and rule[rule.index("-p") + 1] in ("icmp", "ipv6-icmp"):
            continue
        target = rule[rule.index("-j") + 1]
        if target == "RETURN":
            return "RETURN"
        if target in ("ACCEPT", "DROP", "REJECT"):
            return target
        outcome = verdict(state, source, port, target)
        if outcome != "RETURN":
            return outcome
    return "ACCEPT" if chain == "INPUT" else "RETURN"


class Fail2banCompatibilityTest(unittest.TestCase):
    def bash(self, body):
        return subprocess.run(["bash", "-c", f"source {shlex.quote(str(SCRIPT))}\n" + body],
                              text=True, capture_output=True, cwd=ROOT)

    def fixture(self, directory):
        definitions = []
        for command, source in (("iptables", "203.0.113.8/32"), ("ip6tables", "2001:db8::8/128")):
            state = {"INPUT": [["-p", "tcp", "-m", "multiport", "--dports", "22022", "-j", F2B]],
                     F2B: [["-s", source, "-j", "REJECT"], ["-j", "RETURN"]]}
            path = Path(directory) / (command + ".json")
            path.write_text(json.dumps(state))
            definitions.append(f"{command}() {{ {shlex.quote(sys.executable)} {shlex.quote(str(FIXTURE))} {shlex.quote(str(path))} \"$@\"; }}")
        return "\n".join(definitions) + "\npersist_iptables_rules() { :; }\n"

    def test_new_input_allow_and_allow_all_do_not_bypass_bans(self):
        with tempfile.TemporaryDirectory() as directory:
            result = self.bash(self.fixture(directory) + "iptables_apply_tagged_port open 22022 tcp\niptables_apply_allow_all\n")
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            for command, banned, normal in (("iptables", "203.0.113.8", "203.0.113.9"), ("ip6tables", "2001:db8::8", "2001:db8::9")):
                state = json.loads((Path(directory) / (command + ".json")).read_text())
                self.assertEqual(state["INPUT"][0][-1], F2B)
                self.assertEqual(verdict(state, banned, 22022), "REJECT")
                self.assertEqual(verdict(state, normal, 22022), "ACCEPT")

    def test_lockdown_and_source_whitelist_preserve_fail2ban_first(self):
        with tempfile.TemporaryDirectory() as directory:
            body = self.fixture(directory) + """
for command in iptables ip6tables; do
    ensure_access_framework "$command"
    "$command" -A ALLENTOOL_IP_ALLOW -j ACCEPT
    build_lockdown_chain "$command" 'tcp 22022'
done
iptables_apply_tagged_port open 22022 tcp
iptables_apply_allow_all
"""
            result = self.bash(body)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            for command, banned in (("iptables", "203.0.113.8"), ("ip6tables", "2001:db8::8")):
                state = json.loads((Path(directory) / (command + ".json")).read_text())
                self.assertEqual(state["INPUT"][0][-1], F2B)
                self.assertEqual(verdict(state, banned, 22022), "REJECT")

    def test_persistence_excludes_temporary_chains_without_touching_live_rules(self):
        raw = """# Generated by iptables-save
*filter
:INPUT ACCEPT [0:0]
:f2b-vpstools-sshd - [0:0]
:f2b-other - [0:0]
:ALLENTOOL_INPUT - [0:0]
:DOCKER-USER - [0:0]
-A INPUT -p tcp -m multiport --dports 22022 -j f2b-vpstools-sshd
-A INPUT -g f2b-other
-A INPUT -j ALLENTOOL_INPUT
-A ALLENTOOL_INPUT -p tcp --dport 22022 -j ACCEPT
-A INPUT -m comment --comment "mentions -j f2b-other" -j ACCEPT
-A f2b-vpstools-sshd -s 203.0.113.8/32 -j REJECT
-A f2b-vpstools-sshd -j RETURN
-A f2b-other -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
"""
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / "raw"
            source.write_text(raw)
            rules = Path(directory) / "rules"
            body = f"""
IPTABLES_RULES_DIR={shlex.quote(str(rules))}
iptables-save() {{ cat {shlex.quote(str(source))}; }}
ip6tables-save() {{ cat {shlex.quote(str(source))}; }}
save_static_iptables_rules
"""
            result = self.bash(body)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            for family in ("v4", "v6"):
                path = rules / ("rules." + family)
                filtered = path.read_text()
                self.assertNotIn(":f2b-", filtered)
                self.assertNotIn("-A f2b-", filtered)
                self.assertNotIn("--dports 22022 -j f2b-", filtered)
                self.assertNotIn("-A INPUT -g f2b-", filtered)
                self.assertIn('"mentions -j f2b-other"', filtered)
                self.assertIn("-A DOCKER-USER -j RETURN", filtered)
                self.assertIn("-A INPUT -j ALLENTOOL_INPUT", filtered)
                self.assertEqual(path.stat().st_mode & 0o777, 0o600)
            self.assertEqual(source.read_text(), raw)

    def test_failed_ipv6_snapshot_preserves_both_existing_files(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for family in ("v4", "v6"):
                (root / ("rules." + family)).write_text("keep")
            result = self.bash(f"""
IPTABLES_RULES_DIR={shlex.quote(directory)}
iptables-save() {{ printf '*filter\\n:INPUT ACCEPT [0:0]\\nCOMMIT\\n'; }}
ip6tables-save() {{ return 1; }}
save_static_iptables_rules
""")
            self.assertNotEqual(result.returncode, 0)
            for family in ("v4", "v6"):
                self.assertEqual((root / ("rules." + family)).read_text(), "keep")

    def test_ssh_sync_hook_calls_only_installed_tool_with_managed_config(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            config = root / "managed.local"
            tool = root / "f2btool"
            tool.write_text('#!/usr/bin/env bash\nprintf "HOOK %s\\n" "$*"\n')
            tool.chmod(0o755)
            result = self.bash(f"""
F2B_CONFIG={shlex.quote(str(config))}
F2B_TOOL={shlex.quote(str(tool))}
sync_fail2ban_ports
touch "$F2B_CONFIG"
sync_fail2ban_ports
""")
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertEqual(result.stdout, "HOOK sync-ports\n")


if __name__ == "__main__":
    unittest.main()
